version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    extra_hosts:
    - "host.docker.internal:host-gateway"
